#!/bin/sh

make clean && make
/opt/FunKey-sdk/bin/arm-funkey-linux-musleabihf-strip psnes

if  [ ! -f psnes ]; then
    echo 'Build failed!'
    exit
fi

rm -f *.opk
mksquashfs psnes opk/* pocketsnes_v1.2.3_funkey-s.opk -all-root -noappend -no-exports -no-xattrs
md5sum psnes
make clean
